# Site wide configuration

title: Site Title
locale: en_US
logo: # filename of a logo image that has been placed into your images directory

# Enter the following platform usernames if you would like for them to appear on your site.
owner:
  name: Micah Vandegrift
  avatar: http://lib.ncsu.edu/sites/default/files/vandegrift-2-2_0.jpg
  bio: "Micah Vandegrift’s research focuses on the evolution of research policies and technologies that maximize the dissemination and impact of publicly engaged scholarship. Specifically, he is developing a concept of “translation” as a form of scholarly communication, and exploring evaluation of new forms of scholarly output. As NC State University Libraries first Open Knowledge Librarian, Micah is dedicated to building programs and processes for the research and learning community to embrace a more open scholarly praxis. He is the lead Principal Investigator for Visualizing Digital Scholarship in Libraries and Learning Spaces (Immersive Scholar) funded by a grant from the Andrew W. Mellon Foundation, and studied open science policy and infrastructure in The Netherlands and Denmark as a Fulbright-Schuman Research Fellow in 2018-2019.."
  email: mlvandeg@ncsu.edu
  # Do not include the @ symbol in your Twitter username
  twitter: micahvandegrift
  linkedin: micahvandegrift
  github: micahvandegrift
  orcid: # ID Number (ex. 0000-0000-0000-0000)
  researchgate: #username
  mendeley: #username
  google:
    plus: #username
    analytics:
    verify:
    scholar: #id
  facebook: #username
  instagram: #username
  bing-verify:
  stackoverflow: #123456/username from a "https://stackoverflow.com/users/123456/username" link
  xing: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
  disqus-shortname:

# The following adjust the accents for your site. If you would like to further edit colors, fonts, font sizes, etc.
# you may do so in _sass/variables.scss
highlight-color: '#CC0000'
lowlight-color: '#000'

  # NOTE: If you would like your site to be licensed under a creative commons license, uncomment the 'yes' next to the type of license you wish to use.
creative-commons:
  cc-by: yes
  cc-by-nc: #yes

#DO NOT EDIT BEYOND THIS POINT
# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
